# Generated by Django 5.1.4 on 2026-06-07 07:14

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/')),
                ('description', models.TextField(blank=True)),
                ('country_of_origin', models.CharField(blank=True, max_length=80)),
                ('founded_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='brands/hero/')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='catalog.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ('display_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('sku', models.CharField(db_index=True, max_length=40, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('story', models.TextField(blank=True, help_text='Editorial brand story shown on PDP')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('low_stock_threshold', models.PositiveIntegerField(default=3)),
                ('track_inventory', models.BooleanField(default=True)),
                ('is_in_stock', models.GeneratedField(db_persist=True, expression=models.Case(models.When(stock_quantity__gt=0, then=models.Value(True), track_inventory=True), default=models.Value(True), output_field=models.BooleanField()), output_field=models.BooleanField())),
                ('volume_ml', models.PositiveIntegerField(default=50, help_text='Bottle volume in ml')),
                ('concentration', models.CharField(choices=[('EDP', 'Eau de Parfum'), ('EDT', 'Eau de Toilette'), ('parfum', 'Parfum'), ('cologne', 'Cologne'), ('body', 'Body Mist')], default='EDP', max_length=20)),
                ('gender', models.CharField(choices=[('unisex', 'Unisex'), ('men', 'Men'), ('women', 'Women'), ('neutral', 'Neutral')], default='unisex', max_length=20)),
                ('fragrance_family', models.CharField(choices=[('floral', 'Floral'), ('oriental', 'Oriental'), ('woody', 'Woody'), ('fresh', 'Fresh'), ('citrus', 'Citrus'), ('fougere', 'Fougère'), ('chyp\x08pre', 'Chypre'), ('gourmand', 'Gourmand'), ('leather', 'Leather'), ('aquatic', 'Aquatic')], default='floral', max_length=20)),
                ('top_notes', models.JSONField(blank=True, default=list, help_text="['bergamot', 'pink pepper']")),
                ('heart_notes', models.JSONField(blank=True, default=list)),
                ('base_notes', models.JSONField(blank=True, default=list)),
                ('ingredients', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_bestseller', models.BooleanField(db_index=True, default=False)),
                ('is_new_arrival', models.BooleanField(db_index=True, default=False)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('sales_count', models.PositiveIntegerField(default=0)),
                ('meta_title', models.CharField(blank=True, max_length=160)),
                ('meta_description', models.CharField(blank=True, max_length=200)),
                ('meta_keywords', models.CharField(blank=True, max_length=255)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.brand')),
                ('categories', models.ManyToManyField(blank=True, related_name='products', to='catalog.category')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='products/%Y/%m/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product')),
            ],
            options={
                'ordering': ('display_order', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(blank=True, max_length=160)),
                ('body', models.TextField()),
                ('is_verified_purchase', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(db_index=True, default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'is_featured'], name='catalog_pro_is_acti_e6e001_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'is_bestseller'], name='catalog_pro_is_acti_36922b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'is_new_arrival'], name='catalog_pro_is_acti_e4866f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'price'], name='catalog_pro_is_acti_c6e8cf_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand', 'is_active'], name='catalog_pro_brand_i_ca0f3c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['fragrance_family', 'is_active'], name='catalog_pro_fragran_b53573_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['gender', 'is_active'], name='catalog_pro_gender_d2c9f1_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['product', 'is_approved'], name='catalog_rev_product_837d25_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('product', 'user')},
        ),
    ]
